title: Beth Woytas
description:  Resume
url: https://resume.exceptionelle.ca
#host: 0.0.0.0
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
#  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
